dist: trusty
language: node_js
cache: yarn
notifications:
  email: false
branches:
  only:
    - master
    - next
node_js:
  - node
  - v12
  - v10
env:
  - PLAYWRIGHT_OVERRIDE_VERSION=1.1.0
  - PLAYWRIGHT_OVERRIDE_VERSION=latest
before_install:
  - npm install -g yarn coveralls nyc @patrickhulce/scripts
before_script:
  - yarn add -D "playwright@${PLAYWRIGHT_OVERRIDE_VERSION}"
script:
  - yarn rebuild
  - yarn validate
after_success:
  - cat coverage/lcov.info | coveralls || echo 'Failed to upload to coveralls...'

jobs:
  include:
    - stage: release
      node_js: 12
      env:
        - PLAYWRIGHT_OVERRIDE_VERSION=latest
      script: yarn ci-after-success
