# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  pull_request:
  push:
    branches:
      - main
      - next
      - alpha
      - beta

jobs:
  deduplicate:
    name: Deduplicate Jobs
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: same_content_newer

  build:
    name: Build + Test + Release / Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    if: ${{ needs.deduplicate.outputs.should_skip != 'true' }}
    strategy:
      matrix:
        node: ['12', '14', '16']
        playwright: ['1.12.0', 'latest']

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - name: Update to npm 7
        run: npm i -g npm@7 --registry=https://registry.npmjs.org

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install specific Playwright version
        run: |
          npm install playwright@${{ matrix.playwright }}
          npm install @playwright/test@${{ matrix.playwright }}

      - name: Check types, run lint + tests
        run: |
          npm why playwright
          npm why @playwright/test
          npm run validate

      # Only release on Node 14

      - name: Upload Coverage / Release / Playwright
        run: npm run ci-after-success
        if: ${{ matrix.node == '14' && matrix.playwright == 'latest' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Coverage / Release / Playwright Test
        run: |
          npm run prepare:playwright-test
          npm run ci-after-success
        if: ${{ matrix.node == '14' && matrix.playwright == 'latest' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
